# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_shortname', models.CharField(help_text='Enter field documentation', max_length=30)),
                ('comparisions', models.TextField(help_text='Enter the conditions separated by a comma.')),
                ('time_series', models.BooleanField()),
            ],
        ),
    ]
