# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_experimental_setup', models.CharField(help_text='Currently selected experimental conditions', max_length=30)),
            ],
        ),
    ]
