# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holmes', '0002_currentsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='comparisions',
            new_name='comparisons',
        ),
    ]
